let express = require("express");
let router = express.Router();

let user_route = require("./../api/user/index");
let user_group_route = require("./../api/userGroup/index");
let local_route = require("./../auth/local/index");
let attendance_route = require("./../api/attendance/index");
let userHours_route = require("./../api/userHours/index");

let msglist_route = require("./../api/msglist/index");
let list_route = require("./../api/list/index");
let SOD_route = require("./../api/SOD/index");
let applicationLookups_route = require("./../api/ApplicationLookups/index");
let applicationresources_route = require("./../api/ApplicationResources/index");
let permissions_route = require("./../api/permission/index");
let assets_route = require("./../api/assets/index");
let assetTypes_route = require("./../api/assetTypes/index");
let maintenance_route = require("./../api/Maintenance/index");
let run_route = require("./../api/run/index");
let runRange_route = require("./../api/runRange/index");
let gpslog_route = require("./../api/GpsLog/index");
let dashboard_route = require("./../api/dashboard/index");
let workorder_route = require("./../api/workOrder/index");
let notification_route = require("./../api/Notification/index");
let sensorlog_route = require("./../api/sensorLog/index");
let voiceassistant_route = require("./../api/voiceAssistant/index");
let authorize_route = require("../auth/oauth2/index");
let sensorReport_route = require("../api/sensorReport/index");
let devices_route = require("../api/devices/index");
let supportedParams = require("../api/SupportedParams/index");
let SummaryTiles = require("../api/SummaryTiles/index");
router.use("/login", local_route);
router.use("/authorize", authorize_route);
router.use("/users", user_route);
router.use("/userHours", userHours_route);
router.use("/userGroup", user_group_route);
router.use("/attendance", attendance_route);
router.use("/asset", assets_route);
router.use("/runNumber", run_route);
router.use("/runDetail", runRange_route);
router.use("/list", list_route);
router.use("/msglist", msglist_route);
router.use("/SOD", SOD_route);
router.use("/applicationlookups", applicationLookups_route);
router.use("/applicationresources", applicationresources_route);
router.use("/permission", permissions_route);
router.use("/assettype", assetTypes_route);
router.use("/maintenance", maintenance_route);
router.use("/GpsLog", gpslog_route);
router.use("/dashboard", dashboard_route);
router.use("/workorder", workorder_route);
router.use("/notification", notification_route);
router.use("/sensorlog", sensorlog_route);
router.use("/voiceassistant", voiceassistant_route);
router.use("/report",sensorReport_route);
router.use("/devices",devices_route)
router.use("/SupportedParams",supportedParams);
router.use("/SummaryTiles", SummaryTiles);
module.exports = router;
